### ISSUE TITLE
adapt time to local format

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#124]
We should adapt times and dates to local format.

Specially on calendar, but I guess everywhere.

Either we detect users location or we use timezone setting, or we ask user his country to set format ?

**Comment by Shisu** [comment]
Guess best would be, to ask the user which format he/she wants to use.
If no format is chosen, it'll be the default format of the website?
Like this a user on for example vaction won't get confused by different formatting depending on timezones. And you can chose an other format than usual in your country without faking it.

**Comment by climu** [comment]
yea, having user choosing format seems.

Then it's mostly about figuring out about django datetimes formats, building a setting page, and passing such formats to fullcalendar.

I could do that !

**Comment by climu** [comment]
hum... after digging into some docs, it appear python can format date automatically according to locale.
So it might be better to just set a country.

That will deal with both timezone and time format. Also, we could automatically translate the days of the weeks in local language.

And, who knows, one day we could translate the website ^^
