### ISSUE TITLE
Add latests kgs rank next to names

### ISSUE THREAD

**Issue by lmhsjackson** [climu/openstudyroom#125]
Hi there. I am a ruby coder and just joined OSR. And it surprised me that this is not implemented.

Although Python feels like a ruby a close relative I don't feel so confident as to develop this myself (I'll try though).

Basically I think we could hit http://www.gokgs.com/gameArchives.jsp?user=jacksonh parse the html (obviously there are a lot of libs for this) and get the last rank from there (the rank of the player in it's last game).

I would be glad to pair program on this so I could learn some python/django while doing it.

**Comment by climu** [comment]
Hi lmhjackson.

Welcome in OSR and thank you for suggesting this idea and for your will to help out coding !

 We should maybe decide what rank we want next to one player's name. Indeed we are considering supporting other servers (OGS) and some users suggested to have our own OSR rank system. 

Showing players kgs players rank in their profile can certainly be done. We could also add KGS graph.

You should know that we hit KGS archive page of one player every 5 minutes in [here](https://github.com/climu/openstudyroom/blob/master/league/views.py#L31). On top of that, we are already using [beautiful soup ](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) to parse the html [here](https://github.com/climu/openstudyroom/blob/master/league/utils.py#L65). So getting the rank can certainly easily be done.

One other easy solution would be to ask users their rank and they set it themselves.

I might be afk for a couple of days but I am looking forward to discuss that with you.

**Comment by lmhsjackson** [comment]
I am not a fan of letting people say what their rank is, some are too humble, or something like that, I think their ranks in the different servers (we could add ogs later) is way more representative. We could later make it optional to display the ranks. I'll start checking the code and try to get an instance up and running locally. I don't see what our own rank system will bring to the table... but these are all complementary ideas.

**Comment by climu** [comment]
You might be right.
It's almost free for us to get kgs rank. We can add it to users [profile](https://github.com/climu/openstudyroom/blob/master/league/models.py#L625-L638). Then we could display it wherever we want.

Indeed getting a local copy running is first step. Feel free to contact me on discord where we have a room for coding the website.

**Comment by lmhsjackson** [comment]
I am trying to get my local env running but I have the following issue: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-esx0aqei/bitfield/
tryed to install setup tools, but I dont really have an idea of what I am doing, I have some time now, lmk how can I reach you on discord.

**Comment by lmhsjackson** [comment]
my nick on discord is jacksonh and my tag is 6316

**Comment by climu** [comment]
My nick is climu. Maybe easiest is for you to join [OSR discord](https://openstudyroom.org/discord/) ?

As for your issue, have you installed python3-dev ? I think I should add that to the how to.
