### ISSUE TITLE
wgo doesn't like iframe (who does?)

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#19]
When viewing games  in pages like [this one](http://openstudyroom.org/league/3/games/) there is a error popup when you reach the end of the sgf.

Such error doesn't happen when is not iframed. See [here](http://openstudyroom.org/wgo/game/57) for instance.

Since wgo js is loaded on every pages of the website (that is not proper I guess) it might be a conflict between the 2 js files.

I see 2 ways to fix it:

**1: Remove wgo js from pages that doesn't needs it.**

**2 :sgf api and no more iframe:**
- create a sgf api: a view at /league/sgf/id that would just return the sgf datas.
- instead of changing iframe content, we could have a js function **update_wgo(id)** that would get sgf data from sgf api and update the player using [wgo js](http://wgo.waltheri.net/player).

Maybe best would be to apply both since neither using iframe nor loading unneeded js on everypages we want.

**Comment by SolarBear** [comment]
Agreed, doing both would be best. Performance-wise having useless JS is a bad idea, while having a template to import that would inject the required JS file and template code as required.

**Comment by climu** [comment]
Breaking news.

This bug is not related to iframe or js conflict !

Thing is kgs is adding some strange incorrect things at the end of some sgf. See [here](https://gist.github.com/climu/0a44159cecc58c4b986c0c85d160e5dc#file-nas-historment-sgf-L231-L232) for instance.

Removing those 2 lines fix the wgo bugs and doesn't alter the sgf.

Why, oh why kgs is doing that ? I guess it's a bug. Will ask.

**Comment by climu** [comment]
I will be working on clean solution that was mentioned before.
