### ISSUE TITLE
Build custom markdown for wgo in forum

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#21]
Allowing users to show a goban with wgo in our forum could be cool.

One needs to write some custom markdown parser.

Know that our forum is powered by [django-machina](https://github.com/ellmetha/django-machina) and uses [python-markdown2](https://github.com/trentm/python-markdown2).

Know that machina have a [setting](https://django-machina.readthedocs.io/en/stable/settings.html#machina-markup-language) to choose the markup language.

Also, we can find [this](https://django-machina.readthedocs.io/en/stable/customization/recipes/using_another_markup_language.html) that can help in machina doc.

**Comment by Yellephant** [comment]
I will work on a solution for this in python-markdown, as we discussed.

It is not specified in this issue, but we discussed it earlier, and the issue then seemed to really be about the creation of a board for an sgf file.

Could you give a non-general example of what the sgf file and output would look like? If it's an sgf file, would it need to be uploaded to the internet somewhere before being called? What would the exact procedure from start to finished result be for a user?

**Comment by climu** [comment]
Thanks for helping.

Creating a board is really easy. Since [wgo](http://wgo.waltheri.net/player) is loaded on every page, you just need to put this html and the board will be created:

`<div data-wgo="sgf_as_plain_text" >`

you can find an exemple [here](https://github.com/climu/openstudyroom/blob/master/wgo/templates/wgo/wgo_iframe.html#L12)

Our users can already upload a file thanks to django-machina app.

Then they will put [goban]sgf-url[/goban] and the parser should:

1. get sgf data from either a get request or opening a file if sgf is on the server. Let say we put sgf as plain text in a sgf-data python var.
2. Then we should `sgf_data=sgf-data.replace(';B[]',"").replace(';W[]',"")` to help with a [bug](https://github.com/climu/openstudyroom/issues/19#issuecomment-287015449).
3. return html `<div data-wgo="sgf_data" >`

I am sailing in Danemark now but will have more time Monday.

Again, Thanks.

**Comment by climu** [comment]
You asked me a more precise exemple of wgo working in kgs sor here it is:
In this [page](https://openstudyroom.org/league/games/188/), you can view the game felino vs potato.

I put the html of this page in a gist and you can see the wgo div [here](https://gist.github.com/climu/40740bf63716a8af917ba21d158fc35f#file-game-188-felino-potato-html-L1855-L1892). 

For the record, this page is rendered by this [template](https://github.com/climu/openstudyroom/blob/master/league/templates/league/archives_games.html#L65).

I hope it's more clear now with this exemple.

**Comment by climu** [comment]
I did a workaround using [shortcord.js](https://github.com/nicinabox/shortcode.js) in [this template](https://github.com/climu/openstudyroom/blob/master/openstudyroom/templates/forum_conversation/topic_detail.html#L124-L201).

What works now is highlighted in [this forum post](https://openstudyroom.org/forum/forum/announcements-26/topic/how-to-display-gobans-in-our-forums-77/):

- `[goban sgf="sgfurl"]` to display a goban
- optional `move="movenumber"` to set the goban at a precise move number
- when post only have one attachment, one does not need to set the `sgf` parameter.

I am not sure if using this js library is a proper way to deal with that. I fear a python markdown parser would be best. 

What needs to be done:
- [diagram sgf="sgfurl"] to add a static diagram
- [move="movenumber"] to add a link that would set the previous goban position to a specific move.
- [coord="coordinate"] to add a text that when hovered would highlight the specific coordinate in previous goban.

**Comment by climu** [comment]
I made moved the code so it work on post preview and review.
Now the code is in [board_base.html template](https://github.com/climu/openstudyroom/blob/master/openstudyroom/templates/board_base.html#L100-L211).

I change the selector to active shortcode on proper part of the pages: ` $('.post, .post-review, .post-preview ')`.

Seems to work.

**Comment by climu** [comment]
Just shooting a new idea: 'simple=true' optional key to disable the comments and game info on the right and only have a goban with move controls.

**Comment by climu** [comment]
It seems there are some bug in this shortcode.js library.

We are going to switch back to the original idea of a python markdown extension.

**Comment by climu** [comment]
Thanks to @musniro we built a [js parser](https://github.com/climu/openstudyroom/blob/master/wgo/static/wgo/shortcode.js) that parse `[goban some_options=value] some coments [/goban]`. Showcase can be found [here](https://openstudyroom.org/forum/forum/announcements-26/topic/how-to-display-gobans-in-our-forums-77/).

I changed our js parser to [mistune](https://github.com/lepture/mistune) and our markdown js editor to [bootstrap-markdown](https://github.com/toopay/bootstrap-markdown).

Next step will be to hadd a goban showing on js preview. On it.
