### ISSUE TITLE
Forum url seems to be dependent to local language

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#267]
A user (MrMartinke) is having a 404 error on this kind of urls `https://openstudyroom.org/forum/forum/questions-to-master-guo-juan-25/topic/ask-a-question-to-master-guo-juan-5p-how-to-ask-78/`

When translating `topic` into the  Dutch `onderwerp` into the url, he can access the page.

I made a page at `https://openstudyroom.org/topic/` and he have no error at all there.

This suggests me that the issue comes from our forum software ([django machina](https://github.com/ellmetha/django-machina)). I ll open an issue there.

![image](https://user-images.githubusercontent.com/2648653/38770394-d6a2d5a6-4012-11e8-8659-3efd03fc0f36.png)

![image](https://user-images.githubusercontent.com/2648653/38770398-e1285ea6-4012-11e8-9320-b1ecebe3d631.png)

**Comment by raylu** [comment]
is MrMartinke creating the topics or trying to view them? if viewing, what link did he click to get there?

**Comment by climu** [comment]
He is just trying to view a topic. He clicked a link directing to this url from discord: `https://openstudyroom.org/forum/forum/questions-to-master-guo-juan-25/topic/ask-a-question-to-master-guo-juan-5p-how-to-ask-78/`

We have tried viewing other topic and it's the same.

We can ask him but I suspect such urls such as `https://openstudyroom.org/forum/forum/ideas-7/topic/create/` will raise same issue.

**Comment by raylu** [comment]
```
$ curl -I 'https://openstudyroom.org/forum/forum/questions-to-master-guo-juan-25/topic/ask-a-question-to-master-guo-juan-5p-how-to-ask-78/'
HTTP/2 200
[...]
content-language: en
```

```
$ curl -I 'https://openstudyroom.org/forum/forum/questions-to-master-guo-juan-25/topic/ask-a-question-to-master-guo-juan-5p-how-to-ask-78/' -H 'Accept-Language: nl-NL'
HTTP/2 404
[...]
content-language: nl
```

**Comment by climu** [comment]
Thanks I didn't knew how to reproduce.

Can it be an expected behavior ? It sounds not likely to me since it prevent people from sharing urls.

**Comment by raylu** [comment]
I blame https://github.com/climu/openstudyroom/blob/1bdb71b27d5f0997cb3f21bf52ef70ce7d963c4e/openstudyroom/settings/base.py#L114

**Comment by climu** [comment]
But we only have this for forum related urls. `https://openstudyroom.org/topic/` have no such issue.

**Comment by climu** [comment]
I renamed the `machina/locale` folder in our production venv. I am reluctant to call that a fix, but the issue is no more.

**Comment by raylu** [comment]
update https://github.com/climu/openstudyroom/wiki/How-to-set-up-local-deployment ?

**Comment by climu** [comment]
Good call. Done.
