### ISSUE TITLE
Feature request: Discord notification of forum posts

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#274]
Hello, any chance of integrating publications on the website with Discord?  I know this is already done for blog posts, it would be good to see it for forum posts too.  I am finding that when people post an introduction to the forum, it tends to go unnoticed, which does not help to welcome new members.

**Comment by climu** [comment]
Did a fast look and it seems django-machina is sending a signal on pre post [here.](https://github.com/ellmetha/django-machina/blob/81fa43778e25e82d3ee095401242699243f10412/machina/models/fields.py#L159).

So I guess it should be doable without much hassle.

**Comment by climu** [comment]
The permission thing that prevent announcing private forums posts is not handled properly but it work.
