### ISSUE TITLE
Associate OSR logo with URL

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#276]
I'm not sure how, but most websites have their logo associated with the URL, so when someone adds a shortcut to their smartphone, the website's logo gets used, and it is like having it as an app.  Try it for OGS, for instance.  Could this be done for the OSR site, please?

**Comment by raylu** [comment]
https://en.wikipedia.org/wiki/Favicon

**Comment by climu** [comment]
I can set up a favicon but I am not sure we are clear on our logo are we?

**Comment by raylu** [comment]
just change it later

**Comment by climu** [comment]
We need a logo!
![image](https://user-images.githubusercontent.com/2648653/48866392-f8547600-edd2-11e8-81b6-0e253335faa2.png)
