### ISSUE TITLE
OSR Forum bug #1

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#278]
On saving a post there is an error message saying "please try again later", almost always.

**Comment by alexmitrani** [comment]
The specific error message is "Internal server error
Sorry, there seems to be an error. Please try again soon."  I got this error 100% of the time when making changes to existing posts.

**Comment by climu** [comment]
fixed [here](https://github.com/climu/openstudyroom/commit/9530f6cb2916e27177b4b58d13e42fb1cee12af5).
