### ISSUE TITLE
Ordering of tabs in "League"

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#291]
At the moment, the order of the various leagues is random on our website.
It would be nice to have them consistent and in a logical order as proposed by og1L.

**Example 1:**
![chrome_2018-10-18_11-32-26](https://user-images.githubusercontent.com/33361462/47148980-2291b000-d2ca-11e8-8079-05dfc6466cea.png)

**Example 2:**
![chrome_2018-10-18_11-32-51](https://user-images.githubusercontent.com/33361462/47148981-2291b000-d2ca-11e8-83d5-4cd1f21bdcfe.png)

**Comment by climu** [comment]
didn't worked :(

**Comment by climu** [comment]
Idea in referenced commit was to order league by their  `event_type` field.
It seems we need to rename the event type from:
```
    EVENT_TYPE_CHOICES = (
        ('ladder', 'ladder'),
        ('league', 'league'),
        ('meijin', 'meijin'),
        ('dan', 'dan'),
        ('ddk', 'ddk'),
        ('tournament', 'tournament'),
)
```
to
```    EVENT_TYPE_CHOICES = (
        ('0ladder', 'ladder'), #monthly main league
        ('1league', 'league'), # mostly for community leagues
        ('2meijin', 'meijin'), 
        ('3dan', 'dan'),
        ('4ddk', 'ddk'),
        ('tournament', 'tournament'),
)
```


so ordering by `event_choice` will work as expected.
