### ISSUE TITLE
Calendar: Planning game invites are not received or sent

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#293]
I have sent a number of invites (and people have invited me) for games, but I did not receive anything.

**Comment by climu** [comment]
Documentation on that:

https://github.com/climu/openstudyroom/blob/7a005571016bbc7f8ef51ab80b0e68b968af0a26/fullcalendar/templates/fullcalendar/calendar_member.html#L583-L612

In here we are doing a ajax call to this view

https://github.com/climu/openstudyroom/blob/7a005571016bbc7f8ef51ab80b0e68b968af0a26/fullcalendar/views.py#L395-L432
