### ISSUE TITLE
Calendar: When sending an invite, dialogue box does not close

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#294]
When sending an invite for a game using the game planner, the dialogue for sending the invite doesn't close and doesn't show any visual confirmation that an invite has been sent, although the game invite has actually been sent.

![invite](https://user-images.githubusercontent.com/33361462/47857685-31a45200-dde2-11e8-8137-6c3af22cf2e5.png)

**Comment by climu** [comment]
I think it's related to #293 .

We are closing the dialog box on success only.

https://github.com/climu/openstudyroom/blob/7a005571016bbc7f8ef51ab80b0e68b968af0a26/fullcalendar/templates/fullcalendar/calendar_member.html#L598-L610

**Comment by d-korni** [comment]
At least send a message to the user in case of failure? Some visual hint, because I sent 5 or 6, not knowing what had happened.

**Comment by climu** [comment]
Obviously yea.

The thing is the all thing was made by a guy who don't really know js. I fear he still doesn't.
