### ISSUE TITLE
Please allow Fischer time settings in tournament app.  

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#297]
The 9 x 9 tournament starting 19th November will use GoQuest time settings: 3 mins main time plus additional 2 seconds per move with a maximum of 3 minutes.  Please could you modify the tournament app to allow this?  Thanks.

**Comment by climu** [comment]
Done in this [commit](https://github.com/climu/openstudyroom/commit/bda3483a7c458097a73d9baf8aef4eb7d7415b97).
