### ISSUE TITLE
Please check that tournament app will accept GoQuest SGF files

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#298]
An example of a GoQuest SGF file follows: 

(;GM[1]SZ[9]KM[7]RU[Chinese]RE[W+R]
PB[kotarojigo (1802)]
PW[alemitrani (1565)]
;B[ee];W[ce];B[ge];W[dd];B[ed];W[ec];B[fc];W[dc];B[df];W[ff];B[gf];W[ef];B[de];W[gg];B[hg];W[fh];B[hh];W[dg];B[cg];W[ch];B[dh];W[eg];B[bh];W[eh];B[ci];W[cf];B[bf];W[be];B[ae];W[ad];B[af];W[bd];B[fb];W[ah];B[bg];W[di];B[ei];W[fi];B[di];W[bi];B[ai];W[fe];B[fd];W[bi])

Thanks.

**Comment by climu** [comment]
We have no indication of the time setting in this SGF file. An admin could add it manually I guess but that's not ideal.

**Comment by alexmitrani** [comment]
GoQuest has fixed time settings, there are no options so there will be no doubt what they were if the SGF is from GoQuest.

**Comment by climu** [comment]
Mind that there is no way to see if the SGF really is from GoQuest. So we will have to trusts users there. I think that's no big deal.

So I think I ll add a button to skip time-settings check for tournament manual uploads.

**Comment by alexmitrani** [comment]
You make a good point though, because the SGF doesn't indicate that it is from GoQuest either.  I will contact the developer and ask if he could add the name of the server and the URL of the game to the SGF.

**Comment by alexmitrani** [comment]
yes, there are, GoQuest has an option to tweet a game like this: "Go Quest game[9x9] (kotarojigo[1802] VS alemitrani[1565]) http://questgames.net/go9/game/1chmhh8xerje #GoQuest #baduk" which can be used to get the link.

**Comment by climu** [comment]
I added a button that will insert time settings, tag and date to it. SGF will still pas the checks.

![image](https://user-images.githubusercontent.com/2648653/48623231-6222e900-e9a9-11e8-929f-cedc5680df27.png)
