### ISSUE TITLE
Check python version and create a docker

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [climu/openstudyroom#299]
It could be interesting to understand if the site can work with latest python versions and create a docker to launch it in local to work with it without push online and make manual tests.

**Comment by climu** [comment]
I have no knowledge about docker at all. I will look into that. Looking such [docs](https://runnable.com/docker/python/dockerize-your-django-application).

One should know that we can have the project running localy with test datas easily folowing this [tutorial](https://github.com/climu/openstudyroom/wiki/How-to-set-up-local-deployment).

As for python verstion, we could indeed test it with newer version.

**Comment by AlessandroMinoccheri** [comment]
Yes I have seen that page, but dependency could be a problem or version of different package I think. For that I recommend to use docker to have an environment with versions and dependencies equals for all developers and equals to the server that the site uses

**Comment by climu** [comment]
Ok.

Is there a real need to test newer python versions? Because I see compatibility bug coming. I mean it's work and time so I could fix bugs instead. If there is a real gain, why not.

We could render a docker with current prod version as a start?

**Comment by AlessandroMinoccheri** [comment]
Isn't necessary, but I advise you to have always new python version installed to have all updates for security for example
The docker  should be equals to prod version always

**Comment by climu** [comment]
OK.

We recently made quite an update, so I don't think I am going to update prod again now.

I will `pip freeze` from production to create the docker file.
