### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [climu/openstudyroom#300]
Please add the contributing file to help new developers to understand how to open a pull request, from which branch, some conventions etc.

For me is very helpful for this project to get more developers working on it 

[Contributing file](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by climu** [comment]
Thanks for this idea. I made a first version. Feel very free to suggest/correct if you see anything missing/wrong.
