### ISSUE TITLE
openstudyroom.org is offline

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#305]
I'm getting an error message "502 Bad Gateway
nginx/1.10.3"
Confirmed with AgentNeigh.  
Please help!
Thanks

**Comment by alexmitrani** [comment]
@raylu fixed this and these were his comments: 
"it's fixed after $ sudo iptables -I INPUT -s 95.216.172.177 -j DROP
no lol
but our SGF parsing code is hilariously slow
(and the DO droplet we're running off of is a little anemic, but that's not the real problem)
we need a robots.txt stat"

**Comment by alexmitrani** [comment]
the website is back online

**Comment by raylu** [comment]
robots.txt in 586b3d446de654ecbe63ba3b5e33b267a3f10718

long-term, we should fix the `/league/games/123` endpoint
