### ISSUE TITLE
game view is too slow

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#306]
Try https://openstudyroom.org/league/games/3775/ for instance. I have a 10 sec response time.

This view does the job.
https://github.com/climu/openstudyroom/blob/586b3d446de654ecbe63ba3b5e33b267a3f10718/league/views.py#L212-L250

I am thinking we could put the loading of the sgf list from an ajax call. So loading the page would be faster but the sgf list on bottom left would load latter.

Another fix would be using [pagination on server side](https://github.com/climu/openstudyroom/issues/161).

I guess we could also think why the sql query is so slow?

**Comment by raylu** [comment]
I don't think the problem is that the SQL query is slow. you can try to get django to print the query but htop said that python3 was maxing the CPU during this time, so I'd expect the slowness to come from the view code

it's possible that I misread htop or the stats reported that way due to some artifact of the single core setup and multiple simultaneous requests, but I'd rate that at under 50% probability

**Comment by climu** [comment]
Interesting. Apart from the query I don't see what can slow things down.

I am guessing it happen during [template](https://github.com/climu/openstudyroom/blob/master/league/templates/league/archives_games.html) rendering.

Will digg.

**Comment by climu** [comment]
Just try localy and we have a n+1 on discord users. Maybe it's enough?
![image](https://user-images.githubusercontent.com/2648653/48761031-e9bd7000-eca7-11e8-91f2-94ae4e32eb1a.png)

**Comment by climu** [comment]
The query is here.
https://github.com/climu/openstudyroom/blob/96cb851b84c58915401923a51d9ad9bcc4da05d0/league/views.py#L212-L227

The lookup for `discorduser` is made in `user_link` templatetag.
https://github.com/climu/openstudyroom/blob/96cb851b84c58915401923a51d9ad9bcc4da05d0/league/templatetags/league_tags.py#L125-L129

I tried adding `prefetch_related` on the query as below but it doesn't fetch any discord_user data.
```
sgfs = Sgf.objects.defer('sgf_text').filter(league_valid=True).\
    prefetch_related('white', 'black', 'winner').\
    prefetch_related('white__discord_user', 'black__discord_user').\
    select_related('white__profile', 'black__profile').\
    order_by('-date')
```

results in:
![image](https://user-images.githubusercontent.com/2648653/48762973-841fb280-ecac-11e8-8995-9ea9a71f30f6.png)

**Comment by climu** [comment]
hourray 1.6 sec response time!

fixed n+1 on players and results view too.
