### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#313]
"Internal server error
Sorry, there seems to be an error. Please try again soon."

The error occurs when accessing the following page while logged out:
https://openstudyroom.org/tournament/88/

Please have a look.
Thanks!

**Comment by raylu** [comment]
```Dec 08 00:25:52 openstudyroom.org gunicorn[11330]: ["AttributeError: 'AnonymousUser' object has no attribute 'is_league_admin'", '  File "django/core/handlers/exception.py", line 35, in inner', '  File "django/core/handlers/base.py", line 128, in _get_response', '  File "django/core/handlers/base.py", line 126, in _get_response', '  File "tournament/views.py", line 115, in games_view', '  File "django/utils/functional.py", line 216, in inner']```
