### ISSUE TITLE
primary leagues -> secondary leagues

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#314]
it was agreed a while ago that there would be two types of leagues: primary leagues and secondary leagues, with participation in primary leagues being a necessary condition for participating in secondary leagues.  The main monthly league and meijin leagues are the primary leagues.  It has never been implemented. 
As things are, we have people in the ddk league and meijin league but not in the main monthly league, for instance, which doesn't make sense.
 It would be great if someone could implement it.
 Thanks!

**Comment by climu** [comment]
The way I did it is not pretty but it works:

When joining ANY league, a user will automatically join:
- Last **open league** with **no related community** of the type `meijin`
- Last **open league** with **no related community** of the type `ladder`

Cleaner way would be to add a primary flag on leagues. Maybe in the future.

A question raised is user joining a community league will also automatically join both meijin and monthly OSR leagues. I am not sure that it's our intended behavior.

**Comment by climu** [comment]
Reopening because the ugly workaround is not satisfactory. I will implement such design:

- each league have a primary flag. 
- joining a league will:
    - if a community league: join all primary leagues of the community
    - else: join all OSR primary leagues

**Comment by climu** [comment]
Done.

Primary leagues will be **highlighted**

**Comment by alexmitrani** [comment]
A question: are the same rules applied when the leagues of a new month are populated with people who participated in the previous month?  For instance, people who participated in the may fechgo blitz league would qualify for automatic re-inscription in the june fechgo blitz league.  Because the main monthly league and the handicap leagues are primary, these players should be automatically re-inscribed in those, too.  I get the impression it isn't working like that at the moment, and it would be really useful if it could work like that.  At the moment I am having to re-inscribe people via Django Admin which is a pain.  Thanks.

**Comment by climu** [comment]
Good catch: it is not at the moment:

https://github.com/climu/openstudyroom/blob/af0d5e784d39cc2a89dcf6725ec97e763452cb8a/league/views.py#L1310


All this should be a method in models.py :
https://github.com/climu/openstudyroom/blob/af0d5e784d39cc2a89dcf6725ec97e763452cb8a/league/views.py#L464

Then we would just `user.join(league)` or ` league.join(user)`

**Comment by alexmitrani** [comment]
I came up with a simple workaround: setting the minimum number of games to zero for all fechgo leagues.  That way people shouldn't get automatically unsubscribed when they don't play in a league one month, and it shouldn't be necessary to manually add people to leagues on Django anymore.

**Comment by climu** [comment]
Indeed if you want every one to rejoin every league it is the proper way.
