### ISSUE TITLE
A question on simultaneous multiple community game validity

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#323]
If a game is tagged #fechgo (Federación Chilena de Go) and #osr and it is valid for both a fechgo league and an osr league, will it be added to both league tables?  We think it should but we are not sure whether it actually will or not.  Thanks.

**Comment by climu** [comment]
Yes it should. If it doesn't its a bug. I think we can find such games in past communities.

It allow users to choose what leagues they want the game to count just by adding a tag.

**Comment by alexmitrani** [comment]
We confirmed that it is working the way it should - that's great.

**Comment by cspaier** [comment]
Thanks for the test and confirmation.

**Comment by climu** [comment]
Thanks for the test and confirmation.
