### ISSUE TITLE
Checking if "Game Analysis" is disabled in OGS

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#325]
Current rules stipulate that "Game Analysis" should be disabled for OGS games but even if it is enabled the games actually count as league games.

Code should be updated to check for this and also members made aware that this has now been changed/fixed.

**Comment by climu** [comment]
Anyone feels like playing with OGS api?

**Comment by Nick-Hall** [comment]
It looks like it may be as  simple as adding:

```
if game['disable_analysis'] is not True
    continue
```
somewhere in the loop in the [check_ogs](https://github.com/climu/openstudyroom/blob/dev/league/models.py#L807) method.

(opuss)

**Comment by cspaier** [comment]
Nice!

**Comment by Nick-Hall** [comment]
@climu Thanks.  That looks good. Better then my bad python example.  :)

**Comment by climu** [comment]
No worry. Thank you @Nick-Hall you did the hard OGS api part and even located the method!
