### ISSUE TITLE
feature suggestion: customised registration process for external communities

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#326]
We already had two partial sign-ups: someone from Chile signed up for OSR without writing to fechgo, and someone else wrote to fechgo without signing up to OSR.  This suggests that the sign-up process for the fechgo community could do with some improvements.  

I suggest: 
1) adding a tick box or menu to the OSR registration page where they can indicate if they would like to sign up for an external community as well as OSR.  
2) if it is a foreign-language community such as fechgo, the e-mail messages would be customised and written in that language (I would of course be happy to help with this). 
3) There would be a flag on the league admin table indicating external community and community-specific welcome messages for OGS and KGS. 
4) The registration for the external community would ideally be done automatically together with the registration for OSR.  

Would this be possible?  Thanks.  

Alex

**Comment by climu** [comment]
Yes, that is doable.

I will separate the translation issue here and focus on the registration flow. Translating is possible, django have a built-in system for that. We could actually translate many parts of the website. But it doesn't impact the other things. I will edit your issue title to remove the foreign language mention. Please feel free to open a new issue suggesting translation of emails and pages of the website. 

At the moment, the fechgo community is not open. So users can not join it by them self. Maybe I got it wrong, but I think the workflow you suggested would allow anyone to join it.

We could think of something like that perhaps?

1. Adding a multiselect field suggesting all OSR public communities so users can select their interest in communities at registration.
2. Indicate in league-admin that the user have interest in the communities.
3. When the user is validated by OSR team:
    3.1. If community is open: Automatically add the user in the community.
    3.2. If community is closed: show the user in a "new-user" list for community admins with buttons to accept or decline the user. We could possibly email all community admins to inform a new user have interest in their community

**Comment by alexmitrani** [comment]
What you propose sounds good.  Thanks.

**Comment by climu** [comment]
I was thinking that you might see some users clicking on the fechgo community out of curiosity without being a Chilean go player.

You fine with that?

**Comment by alexmitrani** [comment]
I'm fine with that if it is how you described earlier: "If community is closed: show the user in a "new-user" list for community admins with buttons to accept or decline the user. We could possibly email all community admins to inform a new user have interest in their community"

**Comment by climu** [comment]
It's on.
