### ISSUE TITLE
inconsistencies between league admin info and league info displayed to players

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#330]
in the 9x9 league....
on the admin side:
- the komi was set to 5.5
- byo-yomi 30s (minimum 3 periods).  

On the player side, the info page says: 
- komi 6.5
- minimum of 5 * 30s byo-yomi.  
I assumed the admin version was write, we will see if a game with 3 m + 30s with 5.5 komi is league valid or not.
thanks

**Comment by alexmitrani** [comment]
the 9x9 game with 3 mins + 3*30 seconds byo-yomi and komi 5.5 was scraped and considered league valid.

**Comment by climu** [comment]
Thanks for the heads up.

Regarding the komi, it's just that the info page was not reading the setting at all (komi setting was introduce not that long ago). It is fixed now.

Regarding time settings: there is no setting at this time for the number of byo yomi periods. It's hardcoded at `3` but we asked players to set up `5`. That's a bug.

https://github.com/climu/openstudyroom/blob/9a688ff68b15cd9e4dbfd41c4c32e37cf0d13b7d/league/models.py#L490

I fixed the info page so it reflect the actual rules and get rid of inconsistencies.

**Questions remaining is**: Do we want a setting for that? If not, do we want 3 or 5?

**Comment by climu** [comment]
I close since inconsistencies are no more and remind the open question:
Do we want a setting for the number of byoyomi periods? If not, do we want 3 or 5?

**Comment by d-korni** [comment]
I would suggest 5 for 19x19 and 3 for 9x9.

**Comment by alexmitrani** [comment]
See https://github.com/climu/openstudyroom/issues/335
