### ISSUE TITLE
unmark for translation

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#332]
g:i A,M j,n/j/y

thanks

**Comment by climu** [comment]
thanks. For the record you can see where this string is located hovering the original string:
![image](https://user-images.githubusercontent.com/2648653/50736800-15e27100-11c2-11e9-968c-cd01caa63041.png)

**Comment by alexmitrani** [comment]
OK, thanks @climu

**Comment by climu** [comment]
Just need to update catalog files now
