### ISSUE TITLE
"invalid date" when browser requests spanish

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#334]
in the "Federación Chilena de Go Games" table the date is shown as "invalid date" when browser requests Spanish, however the date is shown correctly when browser requests English.

**Comment by alexmitrani** [comment]
![screenshot_20190106-233907](https://user-images.githubusercontent.com/27974470/50746118-549d1900-120c-11e9-8ba1-c651ef00e8d4.png)
screenshot attached.

**Comment by alexmitrani** [comment]
might this be related to #332?

**Comment by climu** [comment]
Thanks Alex.

This is not related to #332 at all. The mentioned issue happens in this template:

https://github.com/climu/openstudyroom/blob/fecd3592b82ddfdbce4315c7f82ccb05ec646ec9/openstudyroom/templates/postman/base_folder.html#L55

While the invalid date issue takes place  in [here](https://github.com/climu/openstudyroom/blob/dev/community/templates/community/community_page.html).

I have faced it [couples times](https://github.com/climu/openstudyroom/issues/42) and will fix it tonight. For the record, we are using datatable js plugin and it needs to parse the date into a moment object. Add localisation to that and well, such issues arise. My usual workaround is to force the date into english format so it can be parsed properly.

**Comment by alexmitrani** [comment]
I'm getting the invalid date issue again.  On the fechgo table of games.

Thanks

**Comment by climu** [comment]
thanks for the head sup!

**Comment by climu** [comment]
I canot reproduce: 
![image](https://user-images.githubusercontent.com/2648653/53681352-b350b180-3ce8-11e9-97d3-5a6c458f78eb.png)

Can you confirm the issue remain?

**Comment by climu** [comment]
I think I have it now!
