### ISSUE TITLE
User search function

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#345]
Add a user search function, where it is possible to search for a user and see their profile page.

**Comment by climu** [comment]
That's a thing I want implemented for ages!

**Comment by climu** [comment]
I built a global search field that looks for users, pages, blog post and forum posts:
![image](https://user-images.githubusercontent.com/2648653/55288449-41878880-53b8-11e9-9193-bb9f156fa528.png)

The UI could be better but it works.
