### ISSUE TITLE
League setting byo-yomi overtime not checked?

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#354]
I played a game with 3x30 seconds byo-yomi periods instead of 5x30 seconds and it still counted for the league. 

Example: https://openstudyroom.org/league/98/games/4250/

**Comment by alexmitrani** [comment]
@d-korni that is consistent with the league rules so it is not a problem: https://openstudyroom.org/league/98/infos/

**Comment by alexmitrani** [comment]
See #330: https://github.com/climu/openstudyroom/issues/330

**Comment by d-korni** [comment]
Okay, that's great. Thanks for the reference. 

I think the team should anounce to the members when changes to the league rules take place though. ;)
