### ISSUE TITLE
league end date implementation seems incorrect

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#355]
the fechgo monthly league was defined as running from jan 1 to jan 31 and it now says it will end in 1 day 6 hours' time, which seems incorrect - there are over 2 days 'til the end of january.  There is a note that says "set to 1 for full month" but when I changed the settings to jan 1 - feb 1 it said the dates were invalid.  I'm stuck.  Please help.

Thanks!

**Comment by climu** [comment]
Hi.
I might be wrong, but the league end date implementation doesn't seems incorrect.

Indeed it is stated that all date happens at 00:00 UTC time. This means if you set the end date to the 31 of the month, the league will be closed the 31 at 00:00. That is at the end of the 30.

This is stated in the form and there is a helper text advising to set end date to the 1st of next month to get full month.

I just changed the end date of the fechgo leagues to the 1st of february.

The remaining issue is: why can't you edit a league end date?

That is an annoying bug I will try to work on.

My guess is it's related to timezones.

Any help welcome here.

**Comment by alexmitrani** [comment]
thanks @climu

**Comment by climu** [comment]
closing this and working on remaining issue in #355

**Comment by alexmitrani** [comment]
I tried changing the browser language preference to english (I had it set to Spanish) but the issue persists.

**Comment by alexmitrani** [comment]
I've been trying to set up the february fechgo league but it won't save it because it says the dates are invalid :-( 
Please could you help with that?  It just needs to be a copy of the existing fechgo "liga mensual" - I was going to call it "liga fechgo febrero 2019".  We're going to discontinue the fechgo DDK league as it has only seen 1 game all month.  Thanks!

**Comment by alexmitrani** [comment]
I've noticed something odd.  Here in Chile we are at UTC-3.  The leagues are supposed to start and end at 00:00 UTC.  So The january league should end at 21:00 in Chile.  However, it is due to end at 20:00 in Chile and I checked this in Django.  So there's something inconsistent there.

**Comment by alexmitrani** [comment]
I tried a few things:
- changed time zone to UK = same error saving league
- changed time zone to UK and browser language to English = league saved OK
- changed browser language to English (time zone UTC-3) = league saved OK
So my preliminary conclusion is that the issue is related to the Spanish translation and not to the time zone.

**Comment by climu** [comment]
This was a mix of different issue. To be clear we seems to have a timezone issue on the ending time right?

**Comment by climu** [comment]
@alexmitrani : Can you confirm this issue remain?

**Comment by alexmitrani** [comment]
I tried to reproduce the issue with browser language set to Spanish but I couldn't reproduce the error.  So I think this can be closed.

**Comment by climu** [comment]
hooray
