### ISSUE TITLE
Can we combine docs/ and the wiki?

### ISSUE THREAD

**Issue by nomadfarmer** [climu/openstudyroom#357]
I propose moving the wiki into docs/ (which I'd be happy to do)
wiki doesn't copy when when you fork the repo, docs/ does.

Another alternative would be to make the wiki editable by anybody (which I assume can be rolled back in the unlikely case of vandalism) while changes to docs/ would require reviewing a PR. But if someone has an old fork, the wiki may no longer match what they have but their version of docs/ should be accurate.

**Comment by climu** [comment]
I agree.

Best would be having all documentation inside the docs folder. If you feel like doing that you are very much welcome.

**Comment by nomadfarmer** [comment]
Cool. I'll probably get on that this afternoon.

**Comment by climu** [comment]
Good job!

See #359.
