### ISSUE TITLE
9x9 on league menu produces an error

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#358]
it points to this page:
https://openstudyroom.org/league/9x9/
and gives this error:

"Internal server error
Sorry, there seems to be an error. Please try again soon."

thanks.

**Comment by nomadfarmer** [comment]
I'm seeing the same on my phone. From the 9x9 tab in any other league page, it seems that the link should be https://openstudyroom.org/league/102/

**Comment by climu** [comment]
We have some "magic views" at `/league/meijin/` , `\league/9x9\` that redirect to last active meijin or 9x9 league.

https://github.com/climu/openstudyroom/blob/6a5b9a64595c0e8ee7801a1d45125cedd825f150/league/views.py#L335-L347

I wouldn't be surprise if the `type` of the 9x9 league was not `league`.

One might think that the league's `type` is not clear at all and he would be right. I added those one after the other without any sort of global thinking.

**Comment by climu** [comment]
Closing this since the bug is no more.

As I said above the type of the leagues are quite a mess at the moment. `league` is for every leagues. `ladder` is for monthly.
