### ISSUE TITLE
Selection of communities as a checkbox?

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#361]
If a user selects a community, they can't de-select it. I guess they have to close page and re-open.
In any case, might be good to de-select.

Also we should a) Add more description of what communities are and b) add a description for each community.

**Comment by climu** [comment]
That's needed indeed.

a) Link to the community page would do? And short sentence? Any suggestion?

b) hum, I could add a tooltip on mouse hover with the first 100 characters of the community description.

**Comment by climu** [comment]
Fair to close this for now?

**Comment by d-korni** [comment]
Check-box looks great and so does the mouse hover.
I would add next to "Communities (optional selection for members of a community using the OSR tools)". Either as a parenthesis or an asterisk and then have the text below the check-boxes. I'm my opinion, it needs to be clear it's optional and describe what communities really are.

**Comment by climu** [comment]
Added a link on "community" a rephrasing and stated that it's optional. Gud?
