### ISSUE TITLE
undeclared length limit to league division name

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#362]
@Kamelotusky was trying to create a community league division with the name "Liga fechgo principiantes (30k - 10k): marzo 2019" and nothing was happening.  We shortened the name several times and eventually with "liga principiantes" the division was created OK.  We concluded that there is a limit on the acceptable length of the division name.  This is OK, but it should be declared somewhere on the user interface or maybe there could be a warning message so that the user knows about it. As it is, it seems like it is a bug because nothing happens for no apparent reason.  Thanks.

**Comment by climu** [comment]
Indeed!

The limit is 20:

https://github.com/climu/openstudyroom/blob/c0ec90ab6446e224f7325e4f0ed333d026ff8806/league/models.py#L976-L979

I will top that to 60 as the League names are.
