### ISSUE TITLE
Handicap

### ISSUE THREAD

**Issue by Tatesin** [climu/openstudyroom#364]
Would it be possible to add the option of having handicap leagues? 
I would like to create a handicap league for the Fechgo community.

Komi preferences would have to be modified too, to accept 6.5 komi in even games, but 0.5 in handicap games.  

I look forward to your reply.

Many thanks!

**Comment by climu** [comment]
Hello!

It is indeed possible. What should be thought beforehand is what we consider a valid handicap. It depends of user ranks and we don't have OSR ranks. I guess we could use the ranks of the server the game is taking place but some KGS players are unranked.

**Comment by alexmitrani** [comment]
I think a simple approach would be to trust the users to only play matches where the handicap is acceptable to both players.  That way the system would not need to worry about that at all.  When setting up leagues there would need to be an option to define whether the rules allows handicap or not.  If handicap is allowed komi of 0.5 should be allowed for handicap games, as well as 6.5 for even games.

**Comment by Tatesin** [comment]
Hello!

Thank you so much for your fast answer and your readiness for helping us!

Please don't hurry this for our sake, we are still discussing if we want to do the league with or without handicap. I was just asking for the possibility of doing it with handicap on the OSR system, I'm sorry if I didn't make myself clear.

I still think it would be good to have the option of doing handicap leagues/tournaments, but please take your time, we are not in a hurry. I can let you know if we are indeed using this option for our next league.

Thank you so much again!

**Comment by climu** [comment]
@alexmitrani : your simple approach sounds reasonable and easy to implement. I think we will go this way.

@Tatesin : Don't be sorry. I like this idea since it both help the fechgo community and offer new possibilities for OSR! I don't feel any rush and will implement it whenever I have time. Feel very free to suggest new idea in github. I like ideas!

**Comment by climu** [comment]
I implemented the approach suggested by @alexmitrani.

Please test it!

**Comment by alexmitrani** [comment]
@climu, a question: if I define a league with max handicap = 25, will games with handicap zero be valid for that league?  I think they shouldn't be valid, because we will also have a league that doesn't accept handicap for games with zero handicap.

**Comment by climu** [comment]
@alexmitrani : 

>  if I define a league with max handicap = 25, will games with handicap zero be valid for that league? 

Yes it is a maximum allowed handicap. Any game with handicap strictly lower than this maximum will pass this test:
https://github.com/climu/openstudyroom/blob/674641e404f6ed9868a4a8232b92a1ab1b55d369/league/models.py#L517

So far it is the only test related to handiap we are doing. 

> Perhaps there could be an option for minimum  handicap?

After your quoted suggestion and our talk on discord, I understood that the following will answer your needs:  I will implement a `league.min_handicap` integer field. Then we will check if `sgf.handicap` is at least greater than `league.min_handicap` for it to be valid. 

I must say I don't really understand the needs here you but am ok to provide tools answering it.

I will also add helper texts about those fields in related leagues forms.

**Comment by alexmitrani** [comment]
thanks @climu

**Comment by climu** [comment]
Sure :)
It's on production now. Let me know!

**Comment by alexmitrani** [comment]
@climu I set up a pilot handicap league to test the new functionality: 
https://openstudyroom.org/league/120/games/
I already found an issue - it won't let me join the league.  I get an error message that says "Oops ! Something went wrong. You didn't join."
Help!

Thanks

**Comment by alexmitrani** [comment]
@climu another thing, in the handicap league a handicap of 1 will be just an ordinary game with komi of 0.5.  The SGF will not record it as a handicap game as such and the HA property may not be present.  Is that considered in the code?    
https://www.red-bean.com/sgf/go.html#properties
Property:	HA
Propvalue:	number
Propertytype:	game-info
Function:	Defines the number of handicap stones (>=2).
		If there is a handicap, the position should be set up with
		AB within the same node.
		HA itself doesn't add any stones to the board, nor does
		it imply any particular way of placing the handicap stones.

Thanks

Alex

**Comment by climu** [comment]
Good call!

I am implementing the following:
If `event.max_handicap > 0` the `sgf.komi` must be `0.5` or `event.komi`.
Else `sgf.komi` must be  `event.komi`.

**Comment by alexmitrani** [comment]
Thanks very much @climu.  From your explanation I understand that when the HA property is missing from an SGF, sgf.handicap will be set to 0.

**Comment by climu** [comment]
Yes. The default SGF handicap is indeed 0. If the HA property is missing, the `sgf.handicap` will be 0.

Your second point stands. There is still an issue. SGF with handicap 1 (komi at 0.5 and handicap to 0) will not pass the test if `event.min_handicap` is set to 1.

I could, check if komi is 0.5 and set `sgf.handicap` to 1 when parsing.

**Comment by alexmitrani** [comment]
@climu that would be a good, pragmatic solution.  Please could you do that?

Thanks

**Comment by climu** [comment]
Done:
https://github.com/climu/openstudyroom/blob/52843fdffd86f1006ee42306a0cd98e696478c6f/league/utils.py#L174-L176

**Comment by alexmitrani** [comment]
Many thanks @climu
