### ISSUE TITLE
please allow longer descriptions on community pages

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#365]
Good day.  We have hit the character limits on https://openstudyroom.org/community/fechgo/ and would like to add some more content to the descriptions.  Please could the word or character limits be extended for both the public and private descriptions?  Many thanks.

**Comment by climu** [comment]
Doubled it from 2000 to 4000 characters.

It's on production already.

**Comment by alexmitrani** [comment]
so quick, thanks very much!
