### ISSUE TITLE
Join button shouldn't be shown if a league have no division

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#370]
Quoting [alemitrani](https://github.com/climu/openstudyroom/issues/364#issuecomment-478183800) from #364 :
> @climu I set up a pilot handicap league to test the new functionality:
> https://openstudyroom.org/league/120/games/
> I already found an issue - it won't let me join the league. I get an error message that says "Oops ! Something went wrong. You didn't join."
> Help!
> 
> Thanks

Thanks @alemitrani. I will try to reproduce as soon as possible.

**Comment by alexmitrani** [comment]
I think I figured out what the problem was - I hadn't created a division.  When I had created a division it let me join the league.

**Comment by climu** [comment]
Happy to hear that!

The join button shouldn't even be there when a league have no division.

I will edit your issue so it reflect the problem.
