### ISSUE TITLE
please adjust "game settings" text to allow for handicap leagues

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#371]
In the fechgo handicap league (https://openstudyroom.org/league/122/infos/) the "game settings" section reads as follows:

Game settings
Game must be played either on the KGS or on the OGS go server.
Game must be public.
**_Games must be played with no handicap_**

Please could you make the handicap part dynamic so that it takes into account whether or not the league allows handicap?  

Many thanks

Alex

**Comment by climu** [comment]
Yup.

Considering replacing with the following if `event.max_handicap > 0`: `Games handicap must be bewteen {{min_handi}} and {{max_handi}} inclusive.`

Feel free to suggest better English ;)

**Comment by alexmitrani** [comment]
that's fine, I just corrected the spelling of "between":

event.max_handicap > 0: Games handicap must be between {{min_handi}} and {{max_handi}} inclusive.

thanks!

**Comment by climu** [comment]
On production already.
