### ISSUE TITLE
Feature suggestion - add support for IGS (Pandanet)

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#380]
I would like to recommend OSR for a future ibero-american (Latin America plus Spain and Portugal) lagged live Go tournament (a league with pre-determined pairings).  However, it is almost certain that the organisers will want to use IGS (Pandanet) because of all it does to promote Go in the region.  In general some people prefer IGS and it would be nice to reach out to them.  How much work would this be?  

Thanks.

**Comment by raylu** [comment]
oh boy https://lifein19x19.com/viewtopic.php?f=33&t=12184

**Comment by alexmitrani** [comment]
I see what you mean
