### ISSUE TITLE
Bug - Sgf viewer context menu appears below viewer board

### ISSUE THREAD

**Issue by AlexSowT** [climu/openstudyroom#417]
Hi there, just noticed this bug whilst using there sgf viewer. If you click on the three black bars to open up the menu, it does not appear above the board, but rather at the bottom of the page, offscreen. 
![image](https://user-images.githubusercontent.com/30374042/103762976-16ac7880-5011-11eb-8484-29965770bdb1.png)

It there appears all the way at the bottom here
![image](https://user-images.githubusercontent.com/30374042/103763025-24fa9480-5011-11eb-84bc-e7e5a34c9138.png)

Bug found on Google Chrome whilst logged in. From this section of the profile page
![image](https://user-images.githubusercontent.com/30374042/103763087-3e9bdc00-5011-11eb-9251-62c661cb81f6.png)

**Comment by climu** [comment]
Thank you for raising this issue.

Maybe it could be some of our css conflicting with [wgo](https://github.com/waltheri/wgo.js)?

I couldn't find any issue about that on wgo repo.

**Comment by AlexSowT** [comment]
The menu is set as position:absoulute, which if disabling moves the menu to below the board. Maybe not the exact solution but i good place to look. 
![image](https://user-images.githubusercontent.com/30374042/103781051-b8da5980-502d-11eb-884b-f75a31c6f0b6.png)

Image after removing position:absolute
![image](https://user-images.githubusercontent.com/30374042/103781140-d3acce00-502d-11eb-863e-11ee65c88efb.png)

**Comment by AlexSowT** [comment]
Could also be worht looking at the top position. At the mometn set to around 2000px, but changing the value to 13% moves it to a much nicer position
![image](https://user-images.githubusercontent.com/30374042/103782248-1f13ac00-502f-11eb-8231-b43de04fe6a2.png)

![image](https://user-images.githubusercontent.com/30374042/103782266-23d86000-502f-11eb-862f-35a512ce58b7.png)

**Comment by climu** [comment]
Was fixed in #418
