### ISSUE TITLE
Group Markdown - Edit Button

### ISSUE THREAD

**Issue by Xen-sits** [climu/openstudyroom#437]
@climu , @LucasBertrand 
League members can't edit their markdown.
It works with admin privileges. 

![image](https://user-images.githubusercontent.com/84234184/118628859-4cd2e380-b7cd-11eb-9896-cea72744e27f.png)

**Comment by climu** [comment]
The button showing logic is here:
https://github.com/climu/openstudyroom/blob/9cc5f99a1824b8fb72dafbbab8a7f316f4194e04/league/templates/league/results.html#L57-L59

and `can_quit` is rendered here:
https://github.com/climu/openstudyroom/blob/9cc5f99a1824b8fb72dafbbab8a7f316f4194e04/league/models.py#L234-L256

`can_quit` will be false when a player has played a game (rightfully). I was lazy to just use that.

Maybe we have a `user.is_in(division)` somewhere to use in the template?
