### ISSUE TITLE
HTTPS for website

### ISSUE THREAD

**Issue by pholthuizen** [climu/openstudyroom#45]
For a system the allows user to register and login with a username and password an HTTPS website is mandatory.

**Comment by climu** [comment]
Hi,
Thanks for raising this issue.

You are indeed right. Thing is we don't know anything about how to set up https. I guess we will start investigating.

If someone feels like helping setting up/managing our debian server, he is welcome.

**Comment by climu** [comment]
Tryed [this](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04).

I installed letsencrypt but I had this issue when running `sudo letsencrypt certonly -a webroot --webroot-path=/var/www/html -d openstudyroom.org`
 .
`IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: openstudyroom.org
   Type:   unauthorized
   Detail: Invalid response from
   http://openstudyroom.org/.well-known/acme-challenge/v-PygDXu1XSAPKOEZVWvmgdBf8t13vzisF8bKzfoYsU:
   "


   <!DOCTYPE html>
   
   <!--[if IE 7]>         <html cl"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.`

Again, I am really inexperienced here.

**Comment by climu** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=openstudyroom.org

A+ Ratting with http redirected to https  !
