### ISSUE TITLE
Create SDK League Slug

### ISSUE THREAD

**Issue by SThornewillvE** [climu/openstudyroom#469]
There is a new SDK League for OSR but no way to automatically link to the active league for the dropdown menu in the website. 

In order to acheive this, we need a new url pattern in [this](https://github.com/climu/openstudyroom/blob/9d59b10e86b6b3279a87dc87fc443f3dc2f85ab4/league/urls.py) file, which will probably look something like this:

`url(r'^sdk/$', views.sdk, name='sdk'),`

There also likely needs to be a new function in "views".

Thank you very much!

**Comment by SThornewillvE** [comment]
The new function needs to be [here](https://github.com/climu/openstudyroom/blob/9d59b10e86b6b3279a87dc87fc443f3dc2f85ab4/league/views.py#L338-L348).

**Comment by climu** [comment]
> There also likely needs to be a new function in "views".
One can take inspiration from:
https://github.com/climu/openstudyroom/blob/9d59b10e86b6b3279a87dc87fc443f3dc2f85ab4/league/views.py#L338-L348
I guess we also need a new `sdk` `event_type`:
https://github.com/climu/openstudyroom/blob/9d59b10e86b6b3279a87dc87fc443f3dc2f85ab4/league/models.py#L33-L39
