### ISSUE TITLE
fixtures have been broken

### ISSUE THREAD

**Issue by fakirsu** [climu/openstudyroom#493]
Hello everyone,
First of all, congratulations and thank you for this very powerful tool, and very useful for go player communities 😉
In the "manual" procedure, everything is fine until the command ./manage.py loaddata fixtures/initial_data.json
which ends with the following error message.
```
  File "/home/orangepi/osr/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
     self.model._meta.object_name
wagtail.core.models.i18n.DoesNotExist: Problem installing fixture '/home/orangepi/osr/openstudyroom/fixtures/initial_data.json': Locale match
```
The server launch command works fine (./manage.py runserver does not generate an error: System check identified no issues (0 silenced).).
But the localhost:8000 site just displays:
> Welcome to your new Wagtail site!

I ask help on discord and a Dev said that he think **the fixtures have been broken for months.**

**Comment by climu** [comment]
Thanks for your interest.
This have been fixed in 0d8cd2c.
