### ISSUE TITLE
better css

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#52]
I think our website could use some css polishing.

I am thinking about our sidebar for instance. I just copy/past css from puput demo.

Feel free to change things in [this folder](https://github.com/climu/openstudyroom/tree/master/openstudyroom/static) and send pull/request.

**Comment by nshiff** [comment]
Hello! Is this still something you're thinking about? I don't actually use the site, but I play go and I am a frontend developer, and I love open source software. 

Which sidebar are you talking about?

**Comment by climu** [comment]
Hi !
Thank you for your interest and your will to help !

This is still something I am thinking about.

The sidebar is the right part of our [homepage](https://openstudyroom.org/) containing boxes: 

- OSR events
-  try OSR game planer
- OSR friends and partner
- ...

Mind that the html is probably very wrong too. As I said I mainly copy and past templates and css from [puput demo](https://github.com/APSL/puput-demo).

Anyway, any effort sanitizing templates and css. Mind that we have boostrap loaded on all website, so you ca use that if you want.

Feel free to ask if you have questions, or submit changes so I can test and we discuss it.
