### ISSUE TITLE
Me vs opponent in profile

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#53]
When a logged user browse another user profile, it could be cool if there were a place **opponent VS me**  containing things like:

- stats of games we played together (win/loss).
- list of games we played together.

Just an idea.

**Comment by Shisu** [comment]
Sounds nice, another option which could be nice is the colors both played.
This way you can see if your performance is better with black/white or maybe that the color doesn't matter.

**Comment by climu** [comment]
good idea.

Actually, the all profile page needs to be redesigned I fear (#144).
